---
title: "Master_Clean"
author: "Daniel Schmidle / Ivan Wolansky"
date: "February 16, 2020"
output: html_document
---

```{r}
library(chron)
library(ggmap)
library(dplyr)
library(magrittr)
devtools::install_github("dkahle/ggmap")
```

**Clean Data 1**


```{r}
fire.raw <- read.csv("C:/Users/daniel/Desktop/Fire_Incident_Dispatch_Data.csv", as.is=TRUE)
```

```{r}
#Remove unused columns 
drop <- c("STARFIRE_INCIDENT_ID","COMMUNITYDISTRICT","COMMUNITYSCHOOLDISTRICT","HIGHEST_ALARM_LEVEL","INCIDENT_CLASSIFICATION","FIRST_ASSIGNMENT_DATETIME","FIRST_ACTIVATION_DATETIME","FIRST_ON_SCENE_DATETIME","INCIDENT_CLOSE_DATETIME")

fire <- fire.raw[,!(names(fire.raw) %in% drop)]
head(fire)
```


```{r}

#split date and time into columns with hour 
len <-  nrow(fire)
MONTH <- integer(length = len)
DAY <- integer(length = len)
YEAR <- integer(length = len)
TIME <- character(length = len)

incident_date <- fire$INCIDENT_DATETIME

for(i in 1:len){
  datetime <- unlist(strsplit(incident_date[i], " "))
  date <- datetime[1]
  timeof <- paste(datetime[2],datetime[3])
  date.split <-  unlist(strsplit(date,"/"))
  MONTH[i] <- as.integer(date.split[1])
  DAY[i] <- as.integer(date.split[2])
  YEAR[i] <- as.integer(date.split[3])
  TIME[i] <- as.character(timeof)
}

#change character to time object 
TIME <- as.integer(format(strptime(TIME,format="%I:%M:%S %p"),"%H"))

fire <- cbind(MONTH,DAY,YEAR,TIME,fire)

drop <- "INCIDENT_DATETIME"
fire <- fire[,!(names(fire) %in% drop)]

```

```{r}
head(fire)
```


```{r}
#contains all data cleaned (no long or lats)
clean_fire1 <- fire
save(clean_fire1,file="../output/clean_fire1.RData")
```



**Clean Data 2**


```{r}
# creates a list of addresses that includes the streets, borough, state, and zipcode
addresses <- paste(fire$ALARM_BOX_LOCATION, ", ", fire$INCIDENT_BOROUGH, sep="", ", NY ", fire$ZIPCODE)

# replaces & with AND because it makes geocoding more efficient
addresses <- gsub("&", "AND", addresses)

# removes any ' from address (no apostrophes in addresses)
addresses <- gsub("'", "", addresses)

# adds column of full address to dataframe
fire$FULL_ADDRESS <- addresses

```

```{r}
#### used for the geomapping 
api_key <- readLines("../doc/api_key.txt", n=1)
register_google(key = api_key)
```

```{r}
#### code chunk used in order to populate the file that you can load that is called Fire_UNIQUE_Lat_Long.RData
#### only use if you have an api_key to do this with

# selects all unique addresses
unique_addresses <- unique(fire$FULL_ADDRESS)

# creates a dataframe with all unique addresses and 0s as latitude and longitude values
unique_coordinates_df <- data.frame(unique_addresses, 0, 0, stringsAsFactors = FALSE)

# renames columns
colnames(unique_coordinates_df) <- c("FULL_ADDRESS", "LATITUDE", "LONGITUDE")

# cycles through each unique address and finds the latitutde and longitude and updates the dataframe
for (i in 1:nrow(unique_coordinates_df)) {
  coord <- geocode(unique_coordinates_df$FULL_ADDRESS[i], output = "latlona", source = "google")
  unique_coordinates_df$LATITUDE[i] <- as.numeric(coord[2])
  unique_coordinates_df$LONGITUDE[i] <- as.numeric(coord[1])
}

save(unique_coordinates_df, file="../output/Fire_UNIQUE_Lat_Long.RData")
```


```{r}
load(file="../output/Fire_UNIQUE_Lat_Long.RData")

fire <- merge(fire, unique_coordinates_df, by = "FULL_ADDRESS", all.x = TRUE, all.y = TRUE)

clean_fire2 <- fire

# removes any rows where latitude or longitude are 0
clean_fire2 <- clean_fire2[!(clean_fire2$LATITUDE == 0 | clean_fire2$LONGITUDE == 0),]

#contains cleaned data with full address, longs and lats

#Remove unused columns 
drop <- c("ALARM_BOX_BOROUGH","ALARM_BOX_NUMBER","POLICEPRECINCT","CITYCOUNCILDISTRICT","CONGRESSIONALDISTRICT","DISPATCH_RESPONSE_SECONDS_QY","VALID_DISPATCH_RSPNS_TIME_INDC","INCIDENT_TRAVEL_TM_SECONDS_QY")

clean_fire2 <- clean_fire2[,!(names(clean_fire2) %in% drop)]

save(clean_fire2, file="../output/clean_fire2.RData")
```


**Aggregation of the Number of Incidents by Incident Group at Each Location**


```{r}
# limits found from https://www1.nyc.gov/assets/planning/download/pdf/data-maps/open-data/nybb_metadata.pdf?ver=19d
westlimit <- -74.257159
southlimit <- 40.495992
eastlimit <- -73.699215
northlimit <- 40.915568

# removing any rows that aren't in New York City or the surrounding area
clean_fire2 <- clean_fire2[!((clean_fire2$LATITUDE < southlimit) | (clean_fire2$LATITUDE > northlimit) | (clean_fire2$LONGITUDE < westlimit) | (clean_fire2$LONGITUDE > eastlimit)),]
```

```{r}
# aggregating by latitude, longitude, and classification group and counting the number in each group
count_by_lat_long_incident <- aggregate(FULL_ADDRESS ~LATITUDE+LONGITUDE+INCIDENT_CLASSIFICATION_GROUP, data=clean_fire2, length)

# renaming FULL_ADDRESS column to count (could have chosen any column instead of FULL_ADDRESS above, just chose that one arbitrarily)
colnames(count_by_lat_long_incident)[4] <- "COUNT"

# contains the count data for each group at each location
save(count_by_lat_long_incident, file="../output/incident_count_aggregate.RData")
```



**Firehouse Data**

```{r}
# read in data
firehouses <- read.csv("../data/FDNY_Firehouse_Listing.csv", stringsAsFactors = FALSE)

# save columns to keep
keep <- c("FacilityName", "Latitude", "Longitude")

# remove non-saved columns
firehouses <- firehouses[colnames(firehouses) %in% keep]

# remove rows with NA
firehouses <- firehouses[complete.cases(firehouses),]

# contains the name of each firehouse and its latitude and longitude
save(firehouses, file="../output/firehouse_locations.RData")
```

```{r}
# for heatmap
data = clean_fire2 %>% 
  select(YEAR, MONTH, INCIDENT_CLASSIFICATION_GROUP, LATITUDE, LONGITUDE) %>% 
  mutate(Severity = map_dbl(INCIDENT_CLASSIFICATION_GROUP, ~ switch(.x, 
                                                                    "Structural Fires" = 6, 
                                                                    "NonStructural Fires" = 5, 
                                                                    "Medical Emergencies" = 4, 
                                                                    "NonMedical Emergencies" = 3, 
                                                                    "NonMedical MFAs" = 2, 
                                                                    "Medical MFAs" = 1)))

color = data.frame(
  INCIDENT_CLASSIFICATION_GROUP = c("Structural Fires", "NonStructural Fires", "Medical Emergencies", "NonMedical Emergencies", "NonMedical MFAs", "Medical MFAs"), 
  color = c("#9d2933", "#ff4e20", "#faff72", "#ffc773", "#e9e7ef", "#ffffff"))

incidence <- merge(data, color, by = c("INCIDENT_CLASSIFICATION_GROUP","INCIDENT_CLASSIFICATION_GROUP"), all.y = F)
save(incidence, file="../output/incidence.RData")
```
